version: '3.4'
services:
  auth:
    container_name: auth
    image: auth:1.0.0
    restart: always
    env_file: auth/.env
    ports:
      - "7005:9000"
  seller:
    container_name: seller
    image: seller:1.0.0
    restart: always
    env_file: seller/.env
    ports:
      - "7006:3001"
    volumes:
      - ./seller/poushak.json:/opt/poushak.json
  mongo:
    container_name: mongo
    image: mongo:6.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: poushak
    ports:
      - "7003:27000"
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/mongo.conf:/etc/mongo.conf
    command: ["mongod", "-f", "/etc/mongo.conf"]
  postgres:
    container_name: postgres
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_DB=poushak
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "7000:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "7001:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    links:
      - postgres
  redis:
    container_name: redis
    build: ./redis
    restart: always
    ports:
      - "7002:6379"
    # volumes:
    #   - ./redis/conf:/opt/conf
  nginx:
    container_name: nginx
    image: nginx:1.23.4-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      # - NGINX_HOST=poushak.com
      - NGINX_PORT=80
  swagger:
    container_name: swagger
    build: ./swagger
    ports:
      - "7004:8080"