version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:6.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "7003:27000"
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/mongo.conf:/etc/mongo.conf
    command: ["mongod", "-f", "/etc/mongo.conf"]
  postgres:
    container_name: postgres
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_DB=poushak
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "7000:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "7001:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    links:
      - postgres
  redis:
    container_name: redis
    build: ./redis
    restart: always
    ports:
      - "7002:6379"
    volumes:
      - ./redis/conf:/opt/conf