name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download docgen
      run: curl -o "docgen" https://raw.githubusercontent.com/thedevsaddam/docgen-bin/master/latest/linux_amd64 && chmod +x ./docgen

    - name: Run docgen
      run: ./docgen build -i apis.json -o ./index.html

    - name: Clean artifacts
      run: mkdir public && rm docgen

    - name: Copy Artifacts
      run: tar -cvf github-pages.tar index.html

    - name: Create zip
      run: gzip github-pages.tar && mv github-pages.tar.gz public/

    - name: Deploy Artifacts
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        path: public
        
    
